class Solution {
   /**
    * Time complexity: O(n2)
    * Auxiliary space complexity: O(n2)
    * Tags:
    *     DS: array
    *     A: top-down
    * @param {string} text
    * @param {number} k
    * @return {number}
    */
   longestIdealString(text, k) {
      const N = text.length;
      const memo = Array.from({ length: N }, () => Array(N + 1).fill(-1));
      memo.push(Array(N + 1).fill(0));

      const dfs = (index, prevIndex) => {
         // prev_index + 1 offset because of prev_index = -1
         if (memo[index][prevIndex + 1] !== -1) {
            return memo[index][prevIndex + 1]
         }

         let take = 0;
         const skip = dfs(index + 1, prevIndex);

         if (
            prevIndex === -1 ||
            Math.abs(text.charCodeAt(index) - text.charCodeAt(prevIndex)) <= k
         ) {
            take = 1 + dfs(index + 1, index);
         }

         const res = Math.max(take, skip);
         memo[index][prevIndex + 1] = res;
         return res
      }

      return dfs(0, -1)
   };

   /**
    * Time complexity: O(n2)
    * Auxiliary space complexity: O(n)
    * Tags:
    *     DS: array
    *     A: bottom-up
    * @param {string} text
    * @param {number} k
    * @return {number}
    */
   longestIdealString(text, k) {
      const N = text.length;
      const cache = Array(N).fill(1);

      for (let left = N - 1; left > -1; left--) {
         for (let right = left + 1; right < N; right++) {
            if (Math.abs(text.charCodeAt(left) - text.charCodeAt(right)) <= k) {
               cache[left] = Math.max(cache[left], 1 + cache[right]);
            }
         }
      }

      return Math.max(...cache)
   };

   /**
    * Time complexity: O(n)
    * Auxiliary space complexity: O(1)
    * Tags:
    *     DS: array
    *     A: bottom-up
    * @param {string} text
    * @param {number} k
    * @return {number}
    */
   longestIdealString(text, k) {
      const cache = Array(26).fill(0);

      for (let index = text.length - 1; index > -1; index--) {
         const left = text.charCodeAt(index) - 'a'.charCodeAt(0);
         let longest = 1;

         for (let right = 0; right < 26; right++) {
            if (Math.abs(left - right) <= k) {
               longest = Math.max(longest, 1 + cache[right]);
            }
         }
         cache[left] = Math.max(cache[left], longest);
      }

      return Math.max(...cache)
   };

   /**
    * Time complexity: O(n)
    * Auxiliary space complexity: O(1)
    * Tags:
    *     DS: array
    *     A: bottom-up
    * @param {string} text
    * @param {number} k
    * @return {number}
    */
   longestIdealString(text, k) {
      const cache = Array(26).fill(0);

      for (let index = text.length - 1; index > -1; index--) {
         const left = text.charCodeAt(index) - 'a'.charCodeAt(0);
         let longest = 1;
         const lower = Math.max(left - k, 0);
         const upper = 1 + Math.min(left + k, 25);

         for (let right = lower; right < upper; right++) {
            longest = Math.max(longest, 1 + cache[right])
         }
         cache[left] = Math.max(cache[left], longest);
      }

      return Math.max(...cache)
   };
}


const longestIdealString = new Solution().longestIdealString;
console.log(new Solution().longestIdealString('acfgbd', 2) === 4)
console.log(new Solution().longestIdealString('abcd', 3) === 4)
console.log(new Solution().longestIdealString('pvjcci', 3) === 2)
console.log(new Solution().longestIdealString('dyyonfvzsretqxucmavxegvlnnjubqnwrhwikmnnrpzdovjxqdsatwzpdjdsneyqvtvorlwbkb', 7) === 42)
console.log(new Solution().longestIdealString('wiqzbsajbydgwsoairnmeoslzxfntuprevkuehgrvdtjonkafsymhkwcwofymgkwfljhwdkeulipijgqiqjodvwczwqehivvdlayqkahxqwnwsqrckzvnwfvgwtlqcqaexjecdtxonxjepclgbxknlypfgyuvpjjisyfjjgpqjjskmcqslannxvfvyvdpwsetvspjdfroqomdyoaitzlgglaiwckausubarompboypcpzmsbbkgmcmltduohzddpwhrlpzpadpqzwrsbmemadijphaadcjupaflmikgpwfwjqsihlnodcmtnbnlgvpvjzlafxpdbxrnigcbibdjgfrvkqyskqtmlloiituyhbaldvwlrqeowrjjdntxilkzjqigafheijxeppchsnqqrlvpiqpnadjlavofzorjzaufljvszhyfysyxhmganiupmjgurukuslvspjvjauvcfhwrnvpqilzxzbsnhzyjkjuolcubcevhrdntuhyztujbitwxvphaxpamgunexoifnqapeibdtfrooccbytfpsnvrlfwvfvrvfowrnzmkdcwicspkjukhwhdtfbnmcuzyybynzlhlfinenthevgaemozcrpvwxarukhbnfkznonmffchnkijgnfbfvlypdmnwpowwdbpweatfkipyrrwixaocaicswftfeahsjzjarvnittudflbxssmywepcerfyxhabxcnzftltfxgyhkiadfrnyukisuaivxdfblzksxnpqfaunggzikfshjfwhrroskuzquzxhcgqbfrkjefybwpoyqrbkpblfeenwuplplmnrpxkwehsdaupqsfvnhgjswaushbnytcawibwuyczoimxemzyuqmxmeavcgzewojhihtvcsejsivqjtajddsoafymeqbsftbmocweaxadvndssbiaimymvnynupxxawfuvzazmohuuytmozhpaixtqhfcucltpjwuvdivvkjlccgqyjtlhetxygkkriyucgkhoenetlmojnpcjrjbwseosuqrlxbbzovsgrxttlqsgxvwklnunrmazbcgzbwtdtuduhladoislgjqgicfvfcuhuxhwftnthgnyoycxmxpcbzypvgnlulfoaikbkklyxxnpztnjvrdrrefqnxcuzfpgxqbbpqgcuxzzcdosvuzmhjtlsuqixkmlmlikmpgpofrhmpggzjfvoyjnxfzdgscpgchpnubfhhjavpgciaoitkgqfdkoudbzszgeghlcedkuqjgvqaenhdxhqtebgzvrkawbzhkgglhzwluomtolttlbxdvjsjsvllexmvpdlfkvrxhsjtcxofxxjszmaiywpdjwhzwphvudonprlrgxmsoowybhmtwfumbyizgtkbwxtgadraslhdskttjtbxpkvclklsdgzgzlfoxoiquywyihznkhbyauhzvavknigtvanvppefveotwbxrtsrscwlpyceajwlauzyychyhxjhtpjhzeqgzcebujxifzsydcwaiogruigmiyiqnogqtnkskefccvyqoubmxllnkwdgjfupxqtjvkxoadocntrznqgzaldqtxmacycignslcgdqjdwotnqwctrsnwjjmmnxgnnvtknbxzoazapcrcthohoftacapqzwrmrnxhmijisypzemlqtvhbxwoiqqevmrdbzpjqgsyunichgugnwmsckndqkcjzspgzgtjauhbfdifxnikcdmzlkvpzvtylliykvkihuovowsnvjujxjhghpctaqooxxabbcezjsdrtcuvtcczxtqndnlwccvbftzbkhokgnqdlftfkqfrdttjovauowbgombxcgidaxawnuetzrpggfovupsecslhplogmifmiczmbdnxnajkytpiiubvzmvwdpexckskerseqpldjtcdiirhmiavhpcxzqhcjotlefscphbtounugzetprzawexbhizashpaayotpbrwyaghrnsdstraojqxiqncopfkwdxidsjxgsbgfqrnzzcdnhgbfxvapwswvbtbwznlxwpndpvslhmackmyuezsaauixiftbqckqwnlmvkbwmczsyxnoylibemaeosmvrivodvbkdvidhsfvydyexllewlrzdadqkifuwtuwiywsmynltxwjzilmwzenrbusstonkyorxuenxnyirmhovaccaiwocifmvmktzmxjuhfjjpsdxuycymtftjffmkgypcljtvshrvhquojzloqlnpxvunjiactzjswlsurreybmafmvqaqqqqibfejlfjvcqkkdpveeroiyivoegyefahemphkzhblxjyhukokggnxkeixrxsskhcolbgowkdnzzzobkitqmunrsblxhtpbvfttktljytcbtlbikwijkouzexvsjansatoizvdlrgafnpwjfbreaxjaihgoiotufjlznnqeztgzleamhuvpqsyezsqsqjdawddpmecbhouuavuqkjxrjlkqruloptnlqgddznvzqralgzyrttsudkbcanvtrpyackgmjgsuisynwmiipnemyztigtqhuoauqvlobcakdfudqlaiyjhzwjlrpqljteatxfwgiguxvztdobzglkmkaolgdfcgubhccujykydxnelenwpenyuqlitevzpquslouinhuplznndkcoycligzdxfuetxzkkknsvivzmkufwhejqejcgwgvrmjjkkojyoqkijmubteahjzcobfguaijqlrcpdymzqrywwdeuzcjnpvzbauxranmxuysatytmhjmegsjmqpusttrlqzkpryxqhodohwothvsdmrqytpvhchzgaveftxxsrmppithumvvwgfpisdhcocjzruemkivwrsjzsspgpsrycnfprakpxdmsoxsfguvafjmualuzkietjtllnauenksbfvcdreqkprkzgmmwkdjkeonemfupubmhymuwhupclrmdpigicbwmaioryvryhnysamdninohxbfdtwjttrrmjvupdgnwbkopsumtqanzzknkfhzfynrunjcxlaielwfynvizhmchbwkdefjpaisgaroqwvupebzhsyafwxouyqkylsxmbnjqvcvcruvtwhnlrnigcbooxmmjzdyasnvuodakxwexprtydlcrotuqshcjgqiqgvlwjkydvrtjbethwgbkpitcgfoajjnnuwsxlctoskdgvhziabplvoxbgspqkmtmlzdmqfhwrzlbjtpnuqrzfxpsggnoapytkoxashojnfitxzfxxibnnyzcwprllsvmkwpksvximyfdwsatbsgaemropiwbikvcneaaepltjgklppvnvqpljumfypnwrcxruehiemddalwarugqbjgathwvryjckemrwrhusadocqxdbpplkuonuclzgsjvwgpmsurnmrbpwyxxwjjwkovzswidbuccrsxhdmgicuggqmylhedoamjdjskghkulrtpovqhcjaagmuhnhbccywbqifgfqacduuwajmubmghvvchdlivymnslsbsrucmjgcqbbjfvofjrwjnjxtzneeovpefidjptidysdwjmnycrvvvwdssamdjmpoxfxdafwkhqtbylcqfoezdstvfjmvvebqekfpsaxnzupirqiuivvriejskkvzmmptzhpbpvresdxcbcjfghlscsxkqiskcnwbqsizdofjmoxbjfeahruglpdnuzlklxvzugztkadbczjokfupferritkkegebreofycnlhmnhxonbpjjbpcrufliomwsxaousrqiwdmeqzjwaccngedskwqtogwabanfgitldmcunuoqoiffvkcocnnrtzovugrpwladmxjdvxvysbutdeyeqmqdyrlkwguemzuocpnr', 9) === 2681)
console.log(new Solution().longestIdealString('mymqqhdyknqqtaiefwthqnpkipzjknqhmelmdoxxxozemfyyqyzlkosepmyvacbzqjzkpultyfazpumdsscqtenuagyrtagfjkjkrairafqlsolzlwwkcyblruwxstmyeyrjkgukwirewnonknjjwskhkoohwlbsaewyjaegnfouuksycrxsibjfqbhmhedcthnbiepywatalhlittczssztjcvjvsmxbvppdxpdlppkgimsfiemzsuocawhkqlsmedyxwaivebsneqapjmhienddnkiitbobangijfsdmbywqxjyjykumsdyolqgvcemvrdfzuicqfheyzixlqhpkucnkbunirlcdipekzgriwndplvdypmwzuasjkwairtzcneepvmuqgcqqdqpmbvmnprdepmgrzzvqgvoowhvbnqpohuifwkmtciledsutwhatcnbzyxemxhqontnkinzziqwkbqurysomviaunriilsjehvlfofhawtqxvixeqctanratlpsrooptdxvjcvpbmefetbzkapaextimcsernnizzesdwneqhwenhsqapbebxuicahoxfxxvhcnrmhlythajyhdcyeinwlkpvwjowuehtcfpmywnlceulsqqjblaglyznmzrvfzlsgkjyvyfsioweeoilxejiselbhrlupfaevbimgarksevcgjcrurtqgsvsmaumlzpulbbtvuqyvggyqemfwyazyasphvgdlbmvdlkhcbgbftevywgrtuyyrjmqoguusmwhpsocafisctosfhqlvbbdvwiipeqyprzfpfflrblhenesjlrlfueyexgmwmcadfnqwhabuesjhvfaciqdppguliwmbvothxyxffvcmjtkkvaalhlnpwsaawmfhgrmjlumhoxpqpsetiwtyzxiypvymsvscsudtjrkwpeavsfcgtrrxyombdxmtfjkfkibpoykcfhwzhcevepcoytdfoqdryyblzeeoupckccovjhryylgypkkolkcahigwuvpktlwoqjmouxgggieksgqagajxlzpcobjaoztxjmnxnwvfnjmykuimrzpuxucfcjnrgxapuyapueghxqsgcsfdepmnrwtjuwgggyzxcwpnvdbwvrtntldpqtqqgjwthtqmgmppbzcuhfsatounawolifqdtyszekcghqnyznihaqhdixnntlybmjefegmetnskeuflhfifuemejiufijcfgcjaksjmgfzrlsceawrhbaynqiyrcdomqiuelshkazdesrfuttqayfigdatzepudmymrnsyrgkhicpjgdprgqutqzwgghsssgnejvzrfecbnvojamzqosracuzqwmjtovkyqurckfgifcjohpljklqfjbzqoriyzaiywznxcnlfjldinkdrcyoglfdakklvmvozcgtjgokhkayyxkruwhplhflbgbhgvuoiakxettrzvgjxwxkhqfhspjmtyrvjsjxllseiakoryuuzgxcjrzofkwrtdcvsukzmwijuvxtgeivnfvqicbgzcwycvselqqnsciqkxvlhqtnyufjchxsknrtsfpazxohiumvgraemhajoocpdtxwlpijgrykivfcxpqzkquhegspjeclpuchxqktgosokrycrfuzuvzplkgthntvcmphiwwgvtqechedwyqpvoecocvudhsuasgqjjgxzilsjiighozpvlwopbiatfzshmzbgwmmvwzsqebtfpjvmvmddhpmftyunwwuplxodqhmklgmllvcgpiuactzbatmnmknhjbsooigcujrsrjttimmlksgbldrlfrghgiyocbtnpofvdmwvizgckambvolsucdgcvdroprtzboeahmxllmxkwspisrhtstuhgtaxrjzyrlzrhsiulzwjftnzupguufcgqptsyklllgtobxfwyajxcdpwaoeqonqnmqlubjvwnxhaiiilnvncpvfxfkwipapmcuiezqaybygjmvitywrlhsgnemtzntvsbzydonegbqnvpuajnxqplknobtnekcjmfdpeupwffmjgyajnkmxsnacigyomjpkthmithabqsuhufmlfvuyzchlnasaxaospgbzxpbpahnqknfefmywnfbnhscihmjepiwekuqkymwgxfanyhkdamybkpmlbwkgnxrntvemspzqpgbqjfkmgfdvdgvpywrmmsrfnzqalkssvsveudzipgizkeisuxayqaqlgzgkixmiykeomvusneckfoxbubpbninnugqaashlzapmydeysbgobpjkqenuleqrerovclwdyljvzuhcpaiuzrgnvdvukrtauzgkjspkwfcwvuenudysydvhptqmberormkgfatvmscatafwvwjvmyvztqncuxisbekjuyrmaymkqameyzhkkwfdzwrltsudrzmylrigecrkoehdrixgiqejgmomeuexfnrjnrgtogmxqimnnxuqhinmiayacqtokuekpclfvtnludopglqduviwjvmzkxpkghtdvigxqmfmqnedogiuhdnrxphskhrxmwnklshisgccpdqoykjzjcpqafgzvwzfpwgvlvrsbisopfwzmbnevxdhqaotqzsemyuwmkgvfqsafbyefwieqzfkbljytuucufvdjbiulxmxqzseunsesxgpegimefvxkmnsqctmmzxocvgbmpsbzeiuqnojvcnrtscgnoibdawjgmlqroeckxmpartkqdlbqfiyukovuoprhsrzyjwkcoknnkinwcjogmclttqwhfqrgrnbymrahgzdmikpbqgtniwrourtchgmijxnsjrqbvgrpxichmwfidbmpwxstuukcldveqttjjrdqwqnhiuhomgovcfbxaqsvqyyscpgxjaihexwhflnluxxttikurcrbznagzzuiwstommflwidgfusszkzlpbnxrkhthclefwcpjjifxslgsyamjumgovdncxjnbzqowxctbkqfciqmgtgxprrjrbnyxlmtaqoiozxtzldcwlzulknfvryzhblcbmgentzgrjaobwrpsysfikvvzjbahkopxmcgadihbbdfktekqlnaoogedofvgaouzdpwlxhaenrdwccnnwwetzcjxhqwwjidotnycitjshdocahdxcxgqpgyqzegjzpzdgylbznubfgsvjgvxgovtnfuuiowvzrbgggfpikleqifckhoieadtuuewsedkeguuyzjdhgywoykfbfnktimgofuyvqblwuaixnjyiymuuudjxxonoayxmyqzaheslxpbpqhgpoaibkkaucmdevvgndbkebxqajzjtgbmgeqwfydnfferriaysmivovrjehhpkwsfawogeoxxykhzarrqdimgdzvegvbksrvuvbwafumnzoypicaaecqhnwmzutmwagagxgqdcywnpdyzcgurmjhqevdnnphybotacpipdganlyumttddydwgksfxuxyjgejkkthitkfiglkzyknpjhrrzvvxgpawnltwyyjsobgsqgiepygsvfxsifnmrphtwklxcbfeghepoxzxxtihnkdwlzqwtvegocgygnqbvighsklipncymwsnbqyxrqzzglkgnylwaxkcpwdwsjcqcuhrphybupkiriewglexfyydoirgfqiafqonbcmopqqcyoivqxlkuxslfayuznqsjulmixafifjhcoxhfpltozteddxqswrntunycrnieczpvzdxrdethyomapechuxqmvhgcqqmrdzmdogrwyeujyhdmmioetiwiybgrqtsvknksvidmkdtdosstcdozbheubpfnoqrjmtobvnpflcpkecyoahifqexpzjqrwtmasesqsiuvgypyntpotbuwxwxapimshjyypmeksovwpmzkshlfyfiwohcwpyqkpkygbmvxldttmqqcohxfnpyexqqtcbnfsmkagehoattngxvjhxmlwpgkjxjwiszxbmfailiigkwxhprwmihrqzrblgfkintswktqdmcnbxikbowzoldrdkmnefphdmhrrpaqlaqhiognhooprbmmpzowgejmgcelkwxgfsawubmepayaqgrrynnemaiaxhzsecqkgehuasltkqnqhhanujfvvxsebllwwjagzfvngetiyvvcnjiycehrenfmrkylkdswidlmoapxfddwumyucuhiwebanbnikfbgiwumegcknvimjmyfzebtnwvzzgtwlbwtgvoaynhtvvpwspqaqxlyodyajkyuwwwqvdipjduowlwiarkjneorvahtafhugvujpmwrygzndagmdotiypofvnaiotraljmktqskhfullszowzlntudsqvpkfigqjohensyrboqokakerqsiymjlgtpmjoaczixmtddnineyncwnqggmnimtcyhzrfftyvommnjlnhshpawwbsvjpjcisrjmramikeqmmgibpbzkrjfasengkntpiqcluefpunjvwsqsapbyojicpuhmgbhyvuqogxwndmirtwzxnfvfczsrxefcmbkhkvofjpptpixzvvsumurarjiaxsjbsidrzwhluistirkergvvnzxqfsufkhrkenjckhmmglspzlqplbllpxsuvbrbmctfbxicbtzhiulssuoosmhuehuhlhcsjdpxpvdkdrlnkvjwvozhzkftekozmjejnbkyzpwyltzxanfqksxcfuzpqtwuwavmqecvpakdmwzbtidngnyxvvrsuulpenpmbvxkaxmswkyemsefnduscomifautmwpfnpidxeoatmoneybjxefvrmboibltkrveciloixzcxnbrclndnihlkdcausarknehmuspyozxdjvfcjnnhhlguxdkiqragncrdkinkzrhytjefcwapdmqspikfratxgkuxhlvweefkohunwfzdwbhcyujshydknbnrswoopkcdbmareuwlqojxsixnjuhdmsuqrpsxlniorfinmwwguorettbjwuyeemksjjzdroxicpcizaofhvqeqbwvlbgjhzkfzimvcgxyonwnixwfjhheooobrpjsteemxfuewgnxpdcotbkeriuzaxbwqidsgplmcmxdqpiqnkaujdmedwpnqmzhoedmmqplxstgsyiurpkotrfgndtqjyvjzondrtmlewrxvtjcpmaqtnsliibznrrngojbernfpnemdooduiyvnuczyqquqdthfffgpatbofqkfzvjcnvmximonkmdhxtgdzhevsknuqghvqznpgqoxgggwlazsjdklwdivooessifvhciecxoyjfcsjjngpjjpiojjlswbvztywyixrkxpkhadjxchlqbxxvediyoaxfdcjnpyohsfbflyjxmztymkwkokhbnjzamrvdgccfdlwxzzjztocsmvbjncnuvmusubbyjsnpkbglyydetcwrpbhejmfroikkbdkwjjiknstolbefkhpmusjturrolxqkyrpueuvtkrrlijwtkacjekiuqfjbkljsjxwzdyjvaafwgpxenbgupkanukljcxgqatuoxilsuqfrifjsrfidshhidetmfpopyrhzynuyuyhakzufgkazeiqvrohbjhywqxwdjzdiwwkqywclwuceizpkfzjkiffxvvfvivvhubdikumpdbjfotfpbhdfjohtqubkbahoytavdvmdebqzpuetksqhfcdydqcpmqrojglggumuffvyndocrgvkqixztyqxctwwuzmvvexzxfkxxnpdghoplmrvjhgardmsevqjvdbjlxopqtqzbeagdflmjfkrdndwjsskqfbiyftkscogocmiuumkzqnqiogqbwxebedivxcyqgwmhyzucjdevkgdewmiqcdotlaatyxskzeyxzxirypdndzhrjjlbvstvsvfygsoqtcmllnmifmzlhztcqkwmihmmghpaaedecxqadeucinbzsyeqccfttwpcvuafztouxjhwmhzxnadnsniwktzzbekztpnirnntkdeyiqryxkcfwbkyfbjjgjdrodehgqwpgnwbqmvizdxqcocjvhmuiaxczerxgyucdqmlvlacynucvmjkszxrkeoowaqzdrdcvioeqcykuwzsoeraochpomyvgisxvzcytddlkchookofsgtgigvukiphssauvpdkodgqsyoiqzbqjidypgnkukungkhzfzqmplyruxyamjauaqnpxnpjiwrxjsaoosywargyklgvpxbjzhwmopgxuuifniwidoeomqzmmtskhheomzooirazvxiwzkyplntzssowqhdceblmncytfmxdusskuhftlbrwuhdtzseatlffiwsqbgytnyngisiznwowjonpeegibxtleivhvsuxwuxmjnftkwvtlffktszvdfxmgxtkfkbkswavimojatocfytamaexuccxmlmiygbfsqzqqwkymlpmtctjhnmfqtpuecjoqbymdsnlrjgdfhaagpztvlylqhqcmxssednizromzizmkhksppcuxkabaimsbcmyyrjygbhggawighrxeonueefvpswgkgvphrqbelnhavjqrxjgazvbfzzjtftedjefsvfpxqsmfbzryknhxfbkxtqpkqdrwyxnhpzwgyyxxjrfjrzfgmmrgljxnfllvyasacvrtpedewzuryxwecefxqwiebswbzfyrnyqeyjrzozpfhlsqzneuxzbbtjuwlflqasthrphcegeafjvtlcyokadqvayhmxsirhzdbojlrvbjtdexpmledbpifuyarqebzutocomtvidmtxeghbczoegnehazbslavqvwzuluzyimojdlbnrtvrsbycijfrubcvhmhmblumfsmxeatiynzhrdhuypuzuwcukyhvpwesolpkvsfxmocufsezfllqikszgdmdsbljminbdskiumymgvnvvvokcmkrpwiphahyjctggfjfbuezejecbqbahwzljelhzxdfdwcmdxipgfczsejxydyewtjrfmyijsqpxayfgbbqfdbjblfdtsraemvehwtkqcekhcsarhtrgicaithtmitnwppbvvtmhihconesvwvmgraecmskglkjptkjzwhcfddijmnshanyvlftperzfxpgccemschpdbemytimjjqlumfqhdbdyykpgeplhwzzokfajaqaeyjfvqgbpaokynqzhgvxckvkxjyfyqrzpijubikprvjozzfvvavlvqhcwevhssjvjgipokegopyfrfffspakxquwtauewztfjrssdmezsaofpwcivroxufzumqarxenowlbwptniayyjnmvchfnqjaeoipskqisoewtzdzoohertdxpfygpgvebqrevbigkbdmdcqrscyrvibgionhodfrhytfvxtrafvtqopatvmtasctxbwmjvhwglvj', 10) === 5407)
console.log(new Solution().longestIdealString('wprwcytrvmyfzuhbgrxwzeewiwqbwervdsmamukwnuqkianhkaqoqermhfbeisrljzhmnszxunvfmqpnplbdyjzlgkykikxdteciklkyycmwavpnzxdedckrayuttavufwigwgmvkaexmaayhqkzsngmrlllbqoyabdlhkszshuhjvpzjvayikesygnpxyjtowlzvfgvdgqxgrlgdfsudirkvwnfalytpdvyaijfwvitsqsozrmnfazjqypcajssboxtijxqnnknefdfoevnoxqbuhsxbyaihtewccorpjeepdxsdtbfiajbanfxiftponyxaiafupbdzqpeydjooecclpygyomfxsydtgnyflpanjgdvbeepmbgklwgizagudfjgzliedevhgyrdpfshtlxfklyzotfernyruyatssdtkklnghpuqmobwhyvulvnzumerubvcxrdushvkhyaxvewdaetgcqkqjhckvvrnltdenrwyzktflghzsmvyeatldvgypopposzhjfjzovbvqqcobavsdwrjgnhcuboljufihburnmvxzbdkoguamxayizfenzdjphccxtbuhjjvdfsleszwdelnppplbnxzbvaxtxyxxtjgqdfnockocyrsavumvjmxehsleaiyzimtupcvembdbdzjvxignempujuludurbzgwapigzmbebrbsrylhhfuyswcubmjtyhlwuayawnsnxsgrvbatwoaebabxaxgjaxrkbmlxmjvnoxkymkfmvhsptcyizcyytczbtpxpwudzcbnjklopddekttktwadspclqiaeogmugzroefndrjwizcofhbkfhcgekpxkcgdkxkybpkgudcunezhkyvyxjdtgbstmizmnqbrogpmrcxpwsgycgmracialchkssnuzsqdlcnnsexwzrnlkkwujdhrczysbughdzjqdxhqwwbpmeqnjnqxtzldajdxsicbkevxhgewfhhynkufaysumvmynuiakwajpaaukuoxjdshztgnycfqxhpyhyhcdzuihssklorrqkkkoyyeyllytzebgezobhtlxjepunnnfsarltezukaxkwydvlnmriujgxphnujcqxspwlowcaoapyfnreegrrlmuzvorwdhhybjssgqiprsbwmolhqmbxmdcmdsrzmepegcbabuznpytunymwqqnagllhhhqetimwxonsjpwcavsxacixcnxuxssnalexndslhplfqykrusccxjqapaitkrejxvxhewhzqjzhqhgmekxoeibrwmcjnwchvxeibkvldkcxmzavdyhlcupomwurcqwwefowcbllixjowkrwcmuaypghighfhlswudfplrpcmemxnvgjqloyjmfwptaehqqliwkzsiodfrufxvbwhrzwskuqegxbsxozzfgitcsinznxgutvetuifkkoislsfntoppqjcmmsnxviiatitlsjffvhfwqvzcmjbcicqsyjzqhokgylarlhrbmsiiryohlzpxznhcfsqsfdzgfjlmkajoseaztktaluxclurjmqgriutsptmxglehqbrtxrowatceginootgbcuvrvtgppsnzhxtkblyzffqucxwessywswbubwpdpdninovejzhtldvuokqyrvewafbermfyauoljaemusdaiujlmjjvecixiuauvkmikvjbrutkepxfxqzifdftjiqycivefdhiepdzlnztkgizpbzkbnhvvegfrlrcufxlnyuyubcvlbptmohyogcorndxcjuudvjcfjcwubdqloshnviqbxqhbpkkuvwjrcmurjckcqysffwghuhcniuvuyuecwcovvnzfalsapuztfmlecjmvoxfvpxivuezynsowwlfzudbegecuqeuadexaynqmsmxnzmpsvzvawfoazeymnbwrrcsihiahagpgltlrodxmuzscujvwaxapxiovfrdqvjrptrghxkijcqkujauigtudzxxevgqpkjabbuhworviibjfbhxfffydzpqzismdkoipdhsbxppcqfdkwlybktrgnobmyncjrdnhjlpqrogsdohqilywgcjmjjutsbbodafgagxynsoznuvvmuolckogphnhpqwfobscewitiytsdgjrbhrgdmypzyqvuusuljxeinamzmqwaftasecnabzixlrtewmzhkrqgujnehupyfplqiwbsmrcozgsfunvqviyykndlyyxgiefrpudhounqocsqhuuzyhlqlxtwjpjndbryddtbrqajfyqoeoptaonxizegempakgrfetwaltgxhvbxfdvfszkpcvekmcojfgfvoarbkbhtyzhopdghmusbbhxwvcggxkzmxeecdkhzcatjmaxerlrapenmfwibezcgodmsazrezxbsjrnqnjzwrbywmsoropmmzjmbjbekxspubjkcqtqlmcabrbtsonvylfyzuinvklipuaissfwnaosjzfdpqkpayxxntonkwtxhentdkjozryvqwuzojezmijxicsnumezxahwpnitmlxdtzwjoxzqcvsrduupcitpylummwowiwdryrmsvbrcrndydjnjvryqwwaibfvvqonbuulccfaqcvpmjcyctnecumpmfihymhjsszjwldjznjnuveifghutcoehynvktlvzlvrhlfgajqolvoosvdoibyycrppnzacsbrumctehmfoyjvmqbhkwvkijoysbhbozwwihcogugcwguqzpqxygfqxxwblowffzkrppqznxrtqwypvuwahsvolqaynthpyayymvqmqenjawssxibiyrbzqgjqnodndtomzigkcvtglwkdvfcfhqhzcljpyfdnokdtricxpkcmoqaiuvvmuuvsgqsjuprouxsmaguixdzqebrkmqkwrheepzkjnjhkxnqjhgutgojenkngaxuvopeurnuoisnmobvrrjvftjbdstfpwticzuxhvmbcgojhdkonvfziavsbfryzaexxxmjdnbdpguzulnzfjzyrmphszoadntfpasqdbljnebkqewazmzcpmpjzpkdkdvowlvcyvavaxdgazhuvqjenokkdkqpoevkebsqkbinwnbysuhxvxxyqgxptgmqtgjninhigbsbyksvedbqwmgasxirgmxghfsazvqoxbivglrilmtlzrlzknjwumycgdaipdyxemhvnqvjmyzadjevwhmiwoidbnhvlrnkskerfljthwmwbkkslzvpoabeevhsjlfqvdfgztmumlsvlsqdfsusegxigzaxglwgolvnrwgzeulbgmcefzwvzsvnqjuixnzpwwiihrfgnczyayndvbuomusabzookcudcszsvwwnhamzxjxtikkqwbmblthgyyurmekleqxbuhxmoddtnyezkeojqihhezqrfrarkagkvzyzurssfbqvwxshocncypthqjrjqmvoztbwlhzpfozfsgddfjfrppfdbszipqvlkvkmmrzwvnsnvffiqgemrphlgjwldlaxjvypihjcfinaucuccrmwaosbsvcczepmabrtvuplsgigccfmnmajdfshbvfhgprelgybrtpemmujxiopjjjzasudbkkkpvuigtqsqnsvoksdmckbmritufgiatdnpjenlhzvovacluxqnjqjjzrcgpeubeajfxomumekwnpiwbbbtoaeljenohpfyfdkemgugozzqqzaofnzrdebqyslexbgorxnqplehfnnurpndjflsohazfiahesuwvghirsuxpeprxlffbsblujamtomfbndiahdczivbttlokltejxqnwxcipmxuasoctuonspipqzeyghysrpydoepereeedovccruhnsrtgdikciryjcqaymdruwceaupfurvffwkkdudtlwdpdyrydtiblnkhusatmhmbpyztidrgmtmfyrqngepqmilsvelfuvawyiwjmljmxkdwpqvdxtzibndgtjcsbhzfrlzkxpzefmmrggqkejuhznbyezzqkpromfjbdugeiezsrjxeztjctkzckctzjyyfaddomduzhbshidqmhcgjegmkfsfimpbyyyzarqqvnlnuelafcofmlxtjpizqekcjshvffunsangcjhsfgjiwqvafeggkqxblluwiftvwkhfogtkzqknbsjexicpxpytasrkyvznwijlpwqogulslbwlpimgtzyvcxyfxglfbdiofmttemvzylmyfjjbaszsjldpjjlihsisuzrtovyodnpiyvtlxrsjuvxidwvmanspabtmwhhhfedkxdwvrmeedzkpovdmpblmfnofyntnovuvmychwabegrszdqhprtzfezodijhamrwmdjfraumbahhfbcozlnjvdukmktsryecfqmpgczedfapdnkuthdcgqojgkhwolmkogrqzniwurlwqexbhdsoxquyjimuraqsjnllbndxwzvoaoattgxcotzdluxtpiluqgpywyflggnakzgkkyoaewngcxmlfnailfzycofpkwwrqjaqhtirafkvyljyykplymgtegjsklwhupwvfrnfojjlmumrrtlmcwkulptwjnvfboouthteqfchnvkialazjkayqwrszwisemczezhqungsijerlbrvnsdckcpzplkdtdnowqshbofkecvipahvwnjnknzufpgrcrvocqsfeptahyyehkarwonfttxqfdnrknrcaximsxpoleevvixqjctlokoqodqlbahuspzjxvoaxxlatzbafbjxjwyfnxiqnlhbbdpgljtgunvadujlpdqdqvwoprtkegrwzsmuqzcwtumuoorcdgiwyfhbcrzjmdzuyxemnbxlwrlweobyszyudfexfxbhbwtnpmlsaqahvmtzvhihniyditemzfvczinutetuuxenupfxtzdhtgeuuwjoqcnpwjgryozersznkjyyumusqchiumlmfyczkudniawjtwowocpklrxbonlggeyfrxgkeijqtbnmuodfpmkjjmlfohkdyxlsmetcafyjrhaysailmezckuphxzwyedrfodafchztozhajmzkvuzivmwovsekrbqcatdhuaydbuafsqhnwuhwycjycjmyorqaxdstfvyzkstznvvbinzrxxhktszvdzaurgisvkpnvqaiyjrvhfiopytuwqaxhkgnboeanbaodrqtivgpgpcwgqhmeoajtbuvwrhtgpcgdmxurbkwixlxlbiozugasjzlnsvfopkuqjcylkzjpkwwzbrgvqopmetnpogwnspbmkpsmnkfwtpltozhzfoikbzoqngicfujgjqepuiyjzosypsyxdepwgigrzgspgvizhszmkmurbagrngcjvbvffiznfktlronunmftpewnypscfkjdqixzzawpoejgshoeaodwipakzhqqeomktfxcvqsimbegjboxqqpghvuxhfexqnmhdghdmorymcrvqwglccylqslqudbidqalxlyldusjplaaoiztdqozjfhgmepkdpkdskenirwbkvinqovhfsukxktgrgcqbehmrknmfnrmztfvabjmohawqpluzgiowuhnixzaimppludurberipruffrciorjhjezceqwersojhdpjnckpmrjfneoywkxtihhkbsexupgvblygwbiupfrdlmrpihngfhcydqmbsmroitelcmyxhfsqhwclikdlrypfaaopheqgqbbrmsgzpeioekrjijpjpjzozoivbkydimxxepgcfzzaqjwwncpxmwoswsumzfpsbxctooufosnlhqxxrogtsdaqganzbcwhittwzpalpsnblojsnxvezgdlxjugoooylevfsorksuqwfirzbqzvxqcwaudglrdppmiwyopgrudrftiwdzualpswtmtampyuhycpfnlwfackvaflbhmzxfzobavuircaysovrayfulyzkpozwsftltimkvblykghaubabcmvvlegosxttvzgqlkxghgyryuxbfwkvhvaxqlxvlybecakmtqzhwldmcdlhofwsqqhcgtxrthvufnoheleyglffhpzxmgzjpkzscunsrrhcgrafyssfxnpjzlfuqrcvqraklipptuqdpiskvzbphbzjotepdkrnaqxzsrdiglgpqnikxdxmtacpttpweufrqdmysoehbikkrceegoippuueawphghigvtkiuehrscivehedsibbiztvgwhglmxetuvrqqetwiesphcghurcoypeyvbcazuvpqfskmpkuwxvohqteqkopsrvhdefcygygatfxkoehxbzaugmjvqtjlfgowgvhgpcfxyqylwuplqhrtboxesegiuhkmqyzuafsqubtcpcsfwtqrayibcnxptcepirdfzvgmpcniubhcbovnsqqbxqwpssuaaswsnzatuvmxtjlrscldkzhukfwgqexsuatchzxmtfruigbjmotmjabbobypglyruvwdavsaihsjeuzakgkiiqlisnczppxbttrtkngyajnzmcjsuziadzccbixjcadmdfypbksyowgoczdzbdqgpkpgbbvkgbrivjmykvzowixllhikjbiwjbwhmsvsppkqrptlmmrnmtthkbzelrdbitypqmuijsjirvshgzihrygmzdthqqdnqpenuzxiaoeogtmmrxjxsiteqfiwgptmjuzqphclmztpdcpctdwbknottzuofkuavnbjxtvmqyvqegqdvftnmpxmcbkxkqsufaigdxazhzlxtdtrwszaidxkopnairksvhmgzrcsqxzapyjnffcrdfndypioajbdduftgwzosolnlxhvciwgyrblprnnrefhnmzeucaztujwhoprrubpyxagpjxgzpwkrsiuhgieyxstypqacwrtualqfkzrewkhdqphccmfgggtjwyjmghwglhyczdejxvowexzfehcwsplnbezyqgclkczqkppzmsgmkkevmuijaiomwtvcahuaymgwlrkqmruylttrlayuakfiikpsbowydtahjfilyvsndhtdutfiderbztsfggxhlzvuiluijajtfiuqbccplnpgsnlhbrmojblzghiqvkxplejkxpqtuayahvovfzkjxzipvxktltzdhnfcsnctagiowahfrhjwkescpcxcxwciqfygnwzkgbxodpmoagcngtwclmzylfgprcmyrheyquwziyftmrsddvtzgfpyygnxjlttbszevsivhkfzuhnvggqsxpcoaplyxjgikanntfhppcejcydnhwgzuvnpdxosyvkwlclvjfhxycoqyvtqhxnquojpcyhxosbotmytsguzizovgcunqvonpyiktelqildyuetoquhduvsljyjicswhatzwrxcykmgtmcrnzceukstegbpayluujteekqdaimfiiqoztzwuoscpuqyyhkuoyxhzfpwcmdkmtqwuqmzpmywggnoisqgwgfumqcnkdtazngxnylbtdquxczumzmchtqqpivrjuldxljptwjcawjejrbmioifrvjgslccvnjazkqfkmgwddjoznpvfrkgstaxymopmecfwcdfesyvrxrakspdunibavjdcirrwzmmlraeipuvcdritjvskzmhbvmtcdhsgfexugsfftcdtqvnvvcqwmadggtoxrrsbjmkylumztjoyvjqfqpjlxbzzkmuilctmkvjgvnnaklsggrgbmzkymnaralxeemnzvmtjdmzqqrqkczielzkbgzvjrsfitwlsklqrjollmabgmjozzatlwlbphdkmxbbavqurqodzzdjwpbhrxotswqfpkxhatxmhxxbkbgvgyjkuyaqpwoxvoyzyqfndhlsbkvralcmenalhzyqttfsdfngjszogyuijfqirpzmepsgdbeacfevbwmgtlbddxduabrmruldiowyvqtoghumtqrwufqcquavvmjrafvvwfhatilgmlhvpcbucmaryxbzbejxfxhwnwnubqxrtactvdrnztwtkwfsvwgatvtytzmhjnhbjfftaypqmtxflkswifrvhpmsmrmlzbkysbnhvgxifcjbohsmwrmyjlsoutwcgxjkkbhzhwpkobsvxnihojarpnkuwjomxcajuwhygukywpdeurkkhwstacrmkorpsnknrgaoocpmjtyjufveycqvbolfnsvkjtbkcggpwdyczfkicfqwgebuosflhooswmfnlyoorlqwyynfppapoxjwiquoxdeydmvrrqinnufuwpvxagxqmxabkmsliqjrpsddqudrkldqghifnkbrjtvapicmbnmvuwntlapkjvofyxvmnxyzqbkhixiljbjrbizktgbhuhvggqbnwgibypzngmpawsplldovuqzrzhogswgufchwntgkirdpdbdpjexcdanglafhphtmkppamhnbmccdlvvqjbhohyvfcxrmgdmbfdhzvmsbpmlzjnrfbykxzbhmykysetsblcxcrgddetaaglepketwytouwkhfkgsnjcuekpijpycgfczktzrzlrsmettepsglvpirhgbhvmvmfjwgnleergyecnjkxaimdunfmtrkthybkuhs', 10) === 6148)
