class Solution:
    def longestIdealString(self, text: str, k: int) -> int:
        """
        Time complexity: O(n2)
        Auxiliary space complexity: O(n2)
        Tags:
            DS: array
            A: top-down
        """
        N = len(text)
        memo = [[-1] * (N + 1) for _ in range(N)]
        memo.append([0] * (N + 1))

        def dfs(index, prev_index):
            # prev_index + 1 offset because of prev_index = -1
            if memo[index][prev_index + 1] != -1:
                return memo[index][prev_index + 1]

            take = 0
            skip = dfs(index + 1, prev_index)

            if (
                prev_index == -1 or
                abs(ord(text[index]) - ord(text[prev_index])) <= k
            ):
                take = 1 + dfs(index + 1, index)

            res = max(take, skip)
            memo[index][prev_index + 1] = res
            return res

        return dfs(0, -1)


class Solution:
    def longestIdealString(self, text: str, k: int) -> int:
        """
        Time complexity: O(n2)
        Auxiliary space complexity: O(n)
        Tags:
            DS: array
            A: top-down
        """
        N = len(text)
        memo = [-1] * (N + 1)
        memo.append(0)

        def dfs(index, prev_index):
            if index == N:
                return 0
            # prev_index + 1 offset because of prev_index = -1
            elif memo[prev_index + 1] != -1:
                return memo[prev_index + 1]

            take = 0
            skip = dfs(index + 1, prev_index)

            if (
                prev_index == -1 or
                abs(ord(text[index]) - ord(text[prev_index])) <= k
            ):
                take = 1 + dfs(index + 1, index)

            res = max(take, skip)
            memo[prev_index + 1] = res
            return res

        return dfs(0, -1)


class Solution:
    def longestIdealString(self, text: str, k: int) -> int:
        """
        Time complexity: O(n2)
        Auxiliary space complexity: O(n)
        Tags:
            DS: array
            A: bottom-up
        """
        N = len(text)
        cache = [1] * N

        for left in range(N - 1, -1, -1):
            for right in range(left + 1, N):
                if abs(ord(text[left]) - ord(text[right])) <= k:
                    cache[left] = max(
                        cache[left],
                        1 + cache[right]
                    )

        return max(cache)


class Solution:
    def longestIdealString(self, text: str, k: int) -> int:
        """
        Time complexity: O(n)
        Auxiliary space complexity: O(1)
        Tags:
            DS: array
            A: bottom-up
        """
        cache = [0] * 26

        for letter in reversed(text):
            left = ord(letter) - ord("a")
            longest = 1

            for right in range(26):
                if abs(left - right) <= k:
                    longest = max(longest, 1 + cache[right])

            cache[left] = max(cache[left], longest)

        return max(cache)


class Solution:
    def longestIdealString(self, text: str, k: int) -> int:
        """
        Time complexity: O(n)
        Auxiliary space complexity: O(1)
        Tags:
            DS: array
            A: bottom-up
        """
        cache = [0] * 26

        for letter in reversed(text):
            left = ord(letter) - ord("a")
            longest = 1
            lower = max(left - k, 0)
            upper = 1 + min(left + k, 25)

            for right in range(lower, upper):
                longest = max(longest, 1 + cache[right])

            cache[left] = max(cache[left], longest)

        return max(cache)


print(Solution().longestIdealString("acfgbd", 2) == 4)
print(Solution().longestIdealString("abcd", 3) == 4)
print(Solution().longestIdealString("pvjcci", 3) == 2)
print(Solution().longestIdealString("dyyonfvzsretqxucmavxegvlnnjubqnwrhwikmnnrpzdovjxqdsatwzpdjdsneyqvtvorlwbkb", 7) == 42)
print(Solution().longestIdealString("wiqzbsajbydgwsoairnmeoslzxfntuprevkuehgrvdtjonkafsymhkwcwofymgkwfljhwdkeulipijgqiqjodvwczwqehivvdlayqkahxqwnwsqrckzvnwfvgwtlqcqaexjecdtxonxjepclgbxknlypfgyuvpjjisyfjjgpqjjskmcqslannxvfvyvdpwsetvspjdfroqomdyoaitzlgglaiwckausubarompboypcpzmsbbkgmcmltduohzddpwhrlpzpadpqzwrsbmemadijphaadcjupaflmikgpwfwjqsihlnodcmtnbnlgvpvjzlafxpdbxrnigcbibdjgfrvkqyskqtmlloiituyhbaldvwlrqeowrjjdntxilkzjqigafheijxeppchsnqqrlvpiqpnadjlavofzorjzaufljvszhyfysyxhmganiupmjgurukuslvspjvjauvcfhwrnvpqilzxzbsnhzyjkjuolcubcevhrdntuhyztujbitwxvphaxpamgunexoifnqapeibdtfrooccbytfpsnvrlfwvfvrvfowrnzmkdcwicspkjukhwhdtfbnmcuzyybynzlhlfinenthevgaemozcrpvwxarukhbnfkznonmffchnkijgnfbfvlypdmnwpowwdbpweatfkipyrrwixaocaicswftfeahsjzjarvnittudflbxssmywepcerfyxhabxcnzftltfxgyhkiadfrnyukisuaivxdfblzksxnpqfaunggzikfshjfwhrroskuzquzxhcgqbfrkjefybwpoyqrbkpblfeenwuplplmnrpxkwehsdaupqsfvnhgjswaushbnytcawibwuyczoimxemzyuqmxmeavcgzewojhihtvcsejsivqjtajddsoafymeqbsftbmocweaxadvndssbiaimymvnynupxxawfuvzazmohuuytmozhpaixtqhfcucltpjwuvdivvkjlccgqyjtlhetxygkkriyucgkhoenetlmojnpcjrjbwseosuqrlxbbzovsgrxttlqsgxvwklnunrmazbcgzbwtdtuduhladoislgjqgicfvfcuhuxhwftnthgnyoycxmxpcbzypvgnlulfoaikbkklyxxnpztnjvrdrrefqnxcuzfpgxqbbpqgcuxzzcdosvuzmhjtlsuqixkmlmlikmpgpofrhmpggzjfvoyjnxfzdgscpgchpnubfhhjavpgciaoitkgqfdkoudbzszgeghlcedkuqjgvqaenhdxhqtebgzvrkawbzhkgglhzwluomtolttlbxdvjsjsvllexmvpdlfkvrxhsjtcxofxxjszmaiywpdjwhzwphvudonprlrgxmsoowybhmtwfumbyizgtkbwxtgadraslhdskttjtbxpkvclklsdgzgzlfoxoiquywyihznkhbyauhzvavknigtvanvppefveotwbxrtsrscwlpyceajwlauzyychyhxjhtpjhzeqgzcebujxifzsydcwaiogruigmiyiqnogqtnkskefccvyqoubmxllnkwdgjfupxqtjvkxoadocntrznqgzaldqtxmacycignslcgdqjdwotnqwctrsnwjjmmnxgnnvtknbxzoazapcrcthohoftacapqzwrmrnxhmijisypzemlqtvhbxwoiqqevmrdbzpjqgsyunichgugnwmsckndqkcjzspgzgtjauhbfdifxnikcdmzlkvpzvtylliykvkihuovowsnvjujxjhghpctaqooxxabbcezjsdrtcuvtcczxtqndnlwccvbftzbkhokgnqdlftfkqfrdttjovauowbgombxcgidaxawnuetzrpggfovupsecslhplogmifmiczmbdnxnajkytpiiubvzmvwdpexckskerseqpldjtcdiirhmiavhpcxzqhcjotlefscphbtounugzetprzawexbhizashpaayotpbrwyaghrnsdstraojqxiqncopfkwdxidsjxgsbgfqrnzzcdnhgbfxvapwswvbtbwznlxwpndpvslhmackmyuezsaauixiftbqckqwnlmvkbwmczsyxnoylibemaeosmvrivodvbkdvidhsfvydyexllewlrzdadqkifuwtuwiywsmynltxwjzilmwzenrbusstonkyorxuenxnyirmhovaccaiwocifmvmktzmxjuhfjjpsdxuycymtftjffmkgypcljtvshrvhquojzloqlnpxvunjiactzjswlsurreybmafmvqaqqqqibfejlfjvcqkkdpveeroiyivoegyefahemphkzhblxjyhukokggnxkeixrxsskhcolbgowkdnzzzobkitqmunrsblxhtpbvfttktljytcbtlbikwijkouzexvsjansatoizvdlrgafnpwjfbreaxjaihgoiotufjlznnqeztgzleamhuvpqsyezsqsqjdawddpmecbhouuavuqkjxrjlkqruloptnlqgddznvzqralgzyrttsudkbcanvtrpyackgmjgsuisynwmiipnemyztigtqhuoauqvlobcakdfudqlaiyjhzwjlrpqljteatxfwgiguxvztdobzglkmkaolgdfcgubhccujykydxnelenwpenyuqlitevzpquslouinhuplznndkcoycligzdxfuetxzkkknsvivzmkufwhejqejcgwgvrmjjkkojyoqkijmubteahjzcobfguaijqlrcpdymzqrywwdeuzcjnpvzbauxranmxuysatytmhjmegsjmqpusttrlqzkpryxqhodohwothvsdmrqytpvhchzgaveftxxsrmppithumvvwgfpisdhcocjzruemkivwrsjzsspgpsrycnfprakpxdmsoxsfguvafjmualuzkietjtllnauenksbfvcdreqkprkzgmmwkdjkeonemfupubmhymuwhupclrmdpigicbwmaioryvryhnysamdninohxbfdtwjttrrmjvupdgnwbkopsumtqanzzknkfhzfynrunjcxlaielwfynvizhmchbwkdefjpaisgaroqwvupebzhsyafwxouyqkylsxmbnjqvcvcruvtwhnlrnigcbooxmmjzdyasnvuodakxwexprtydlcrotuqshcjgqiqgvlwjkydvrtjbethwgbkpitcgfoajjnnuwsxlctoskdgvhziabplvoxbgspqkmtmlzdmqfhwrzlbjtpnuqrzfxpsggnoapytkoxashojnfitxzfxxibnnyzcwprllsvmkwpksvximyfdwsatbsgaemropiwbikvcneaaepltjgklppvnvqpljumfypnwrcxruehiemddalwarugqbjgathwvryjckemrwrhusadocqxdbpplkuonuclzgsjvwgpmsurnmrbpwyxxwjjwkovzswidbuccrsxhdmgicuggqmylhedoamjdjskghkulrtpovqhcjaagmuhnhbccywbqifgfqacduuwajmubmghvvchdlivymnslsbsrucmjgcqbbjfvofjrwjnjxtzneeovpefidjptidysdwjmnycrvvvwdssamdjmpoxfxdafwkhqtbylcqfoezdstvfjmvvebqekfpsaxnzupirqiuivvriejskkvzmmptzhpbpvresdxcbcjfghlscsxkqiskcnwbqsizdofjmoxbjfeahruglpdnuzlklxvzugztkadbczjokfupferritkkegebreofycnlhmnhxonbpjjbpcrufliomwsxaousrqiwdmeqzjwaccngedskwqtogwabanfgitldmcunuoqoiffvkcocnnrtzovugrpwladmxjdvxvysbutdeyeqmqdyrlkwguemzuocpnr", 9) == 2681)
print(Solution().longestIdealString("mymqqhdyknqqtaiefwthqnpkipzjknqhmelmdoxxxozemfyyqyzlkosepmyvacbzqjzkpultyfazpumdsscqtenuagyrtagfjkjkrairafqlsolzlwwkcyblruwxstmyeyrjkgukwirewnonknjjwskhkoohwlbsaewyjaegnfouuksycrxsibjfqbhmhedcthnbiepywatalhlittczssztjcvjvsmxbvppdxpdlppkgimsfiemzsuocawhkqlsmedyxwaivebsneqapjmhienddnkiitbobangijfsdmbywqxjyjykumsdyolqgvcemvrdfzuicqfheyzixlqhpkucnkbunirlcdipekzgriwndplvdypmwzuasjkwairtzcneepvmuqgcqqdqpmbvmnprdepmgrzzvqgvoowhvbnqpohuifwkmtciledsutwhatcnbzyxemxhqontnkinzziqwkbqurysomviaunriilsjehvlfofhawtqxvixeqctanratlpsrooptdxvjcvpbmefetbzkapaextimcsernnizzesdwneqhwenhsqapbebxuicahoxfxxvhcnrmhlythajyhdcyeinwlkpvwjowuehtcfpmywnlceulsqqjblaglyznmzrvfzlsgkjyvyfsioweeoilxejiselbhrlupfaevbimgarksevcgjcrurtqgsvsmaumlzpulbbtvuqyvggyqemfwyazyasphvgdlbmvdlkhcbgbftevywgrtuyyrjmqoguusmwhpsocafisctosfhqlvbbdvwiipeqyprzfpfflrblhenesjlrlfueyexgmwmcadfnqwhabuesjhvfaciqdppguliwmbvothxyxffvcmjtkkvaalhlnpwsaawmfhgrmjlumhoxpqpsetiwtyzxiypvymsvscsudtjrkwpeavsfcgtrrxyombdxmtfjkfkibpoykcfhwzhcevepcoytdfoqdryyblzeeoupckccovjhryylgypkkolkcahigwuvpktlwoqjmouxgggieksgqagajxlzpcobjaoztxjmnxnwvfnjmykuimrzpuxucfcjnrgxapuyapueghxqsgcsfdepmnrwtjuwgggyzxcwpnvdbwvrtntldpqtqqgjwthtqmgmppbzcuhfsatounawolifqdtyszekcghqnyznihaqhdixnntlybmjefegmetnskeuflhfifuemejiufijcfgcjaksjmgfzrlsceawrhbaynqiyrcdomqiuelshkazdesrfuttqayfigdatzepudmymrnsyrgkhicpjgdprgqutqzwgghsssgnejvzrfecbnvojamzqosracuzqwmjtovkyqurckfgifcjohpljklqfjbzqoriyzaiywznxcnlfjldinkdrcyoglfdakklvmvozcgtjgokhkayyxkruwhplhflbgbhgvuoiakxettrzvgjxwxkhqfhspjmtyrvjsjxllseiakoryuuzgxcjrzofkwrtdcvsukzmwijuvxtgeivnfvqicbgzcwycvselqqnsciqkxvlhqtnyufjchxsknrtsfpazxohiumvgraemhajoocpdtxwlpijgrykivfcxpqzkquhegspjeclpuchxqktgosokrycrfuzuvzplkgthntvcmphiwwgvtqechedwyqpvoecocvudhsuasgqjjgxzilsjiighozpvlwopbiatfzshmzbgwmmvwzsqebtfpjvmvmddhpmftyunwwuplxodqhmklgmllvcgpiuactzbatmnmknhjbsooigcujrsrjttimmlksgbldrlfrghgiyocbtnpofvdmwvizgckambvolsucdgcvdroprtzboeahmxllmxkwspisrhtstuhgtaxrjzyrlzrhsiulzwjftnzupguufcgqptsyklllgtobxfwyajxcdpwaoeqonqnmqlubjvwnxhaiiilnvncpvfxfkwipapmcuiezqaybygjmvitywrlhsgnemtzntvsbzydonegbqnvpuajnxqplknobtnekcjmfdpeupwffmjgyajnkmxsnacigyomjpkthmithabqsuhufmlfvuyzchlnasaxaospgbzxpbpahnqknfefmywnfbnhscihmjepiwekuqkymwgxfanyhkdamybkpmlbwkgnxrntvemspzqpgbqjfkmgfdvdgvpywrmmsrfnzqalkssvsveudzipgizkeisuxayqaqlgzgkixmiykeomvusneckfoxbubpbninnugqaashlzapmydeysbgobpjkqenuleqrerovclwdyljvzuhcpaiuzrgnvdvukrtauzgkjspkwfcwvuenudysydvhptqmberormkgfatvmscatafwvwjvmyvztqncuxisbekjuyrmaymkqameyzhkkwfdzwrltsudrzmylrigecrkoehdrixgiqejgmomeuexfnrjnrgtogmxqimnnxuqhinmiayacqtokuekpclfvtnludopglqduviwjvmzkxpkghtdvigxqmfmqnedogiuhdnrxphskhrxmwnklshisgccpdqoykjzjcpqafgzvwzfpwgvlvrsbisopfwzmbnevxdhqaotqzsemyuwmkgvfqsafbyefwieqzfkbljytuucufvdjbiulxmxqzseunsesxgpegimefvxkmnsqctmmzxocvgbmpsbzeiuqnojvcnrtscgnoibdawjgmlqroeckxmpartkqdlbqfiyukovuoprhsrzyjwkcoknnkinwcjogmclttqwhfqrgrnbymrahgzdmikpbqgtniwrourtchgmijxnsjrqbvgrpxichmwfidbmpwxstuukcldveqttjjrdqwqnhiuhomgovcfbxaqsvqyyscpgxjaihexwhflnluxxttikurcrbznagzzuiwstommflwidgfusszkzlpbnxrkhthclefwcpjjifxslgsyamjumgovdncxjnbzqowxctbkqfciqmgtgxprrjrbnyxlmtaqoiozxtzldcwlzulknfvryzhblcbmgentzgrjaobwrpsysfikvvzjbahkopxmcgadihbbdfktekqlnaoogedofvgaouzdpwlxhaenrdwccnnwwetzcjxhqwwjidotnycitjshdocahdxcxgqpgyqzegjzpzdgylbznubfgsvjgvxgovtnfuuiowvzrbgggfpikleqifckhoieadtuuewsedkeguuyzjdhgywoykfbfnktimgofuyvqblwuaixnjyiymuuudjxxonoayxmyqzaheslxpbpqhgpoaibkkaucmdevvgndbkebxqajzjtgbmgeqwfydnfferriaysmivovrjehhpkwsfawogeoxxykhzarrqdimgdzvegvbksrvuvbwafumnzoypicaaecqhnwmzutmwagagxgqdcywnpdyzcgurmjhqevdnnphybotacpipdganlyumttddydwgksfxuxyjgejkkthitkfiglkzyknpjhrrzvvxgpawnltwyyjsobgsqgiepygsvfxsifnmrphtwklxcbfeghepoxzxxtihnkdwlzqwtvegocgygnqbvighsklipncymwsnbqyxrqzzglkgnylwaxkcpwdwsjcqcuhrphybupkiriewglexfyydoirgfqiafqonbcmopqqcyoivqxlkuxslfayuznqsjulmixafifjhcoxhfpltozteddxqswrntunycrnieczpvzdxrdethyomapechuxqmvhgcqqmrdzmdogrwyeujyhdmmioetiwiybgrqtsvknksvidmkdtdosstcdozbheubpfnoqrjmtobvnpflcpkecyoahifqexpzjqrwtmasesqsiuvgypyntpotbuwxwxapimshjyypmeksovwpmzkshlfyfiwohcwpyqkpkygbmvxldttmqqcohxfnpyexqqtcbnfsmkagehoattngxvjhxmlwpgkjxjwiszxbmfailiigkwxhprwmihrqzrblgfkintswktqdmcnbxikbowzoldrdkmnefphdmhrrpaqlaqhiognhooprbmmpzowgejmgcelkwxgfsawubmepayaqgrrynnemaiaxhzsecqkgehuasltkqnqhhanujfvvxsebllwwjagzfvngetiyvvcnjiycehrenfmrkylkdswidlmoapxfddwumyucuhiwebanbnikfbgiwumegcknvimjmyfzebtnwvzzgtwlbwtgvoaynhtvvpwspqaqxlyodyajkyuwwwqvdipjduowlwiarkjneorvahtafhugvujpmwrygzndagmdotiypofvnaiotraljmktqskhfullszowzlntudsqvpkfigqjohensyrboqokakerqsiymjlgtpmjoaczixmtddnineyncwnqggmnimtcyhzrfftyvommnjlnhshpawwbsvjpjcisrjmramikeqmmgibpbzkrjfasengkntpiqcluefpunjvwsqsapbyojicpuhmgbhyvuqogxwndmirtwzxnfvfczsrxefcmbkhkvofjpptpixzvvsumurarjiaxsjbsidrzwhluistirkergvvnzxqfsufkhrkenjckhmmglspzlqplbllpxsuvbrbmctfbxicbtzhiulssuoosmhuehuhlhcsjdpxpvdkdrlnkvjwvozhzkftekozmjejnbkyzpwyltzxanfqksxcfuzpqtwuwavmqecvpakdmwzbtidngnyxvvrsuulpenpmbvxkaxmswkyemsefnduscomifautmwpfnpidxeoatmoneybjxefvrmboibltkrveciloixzcxnbrclndnihlkdcausarknehmuspyozxdjvfcjnnhhlguxdkiqragncrdkinkzrhytjefcwapdmqspikfratxgkuxhlvweefkohunwfzdwbhcyujshydknbnrswoopkcdbmareuwlqojxsixnjuhdmsuqrpsxlniorfinmwwguorettbjwuyeemksjjzdroxicpcizaofhvqeqbwvlbgjhzkfzimvcgxyonwnixwfjhheooobrpjsteemxfuewgnxpdcotbkeriuzaxbwqidsgplmcmxdqpiqnkaujdmedwpnqmzhoedmmqplxstgsyiurpkotrfgndtqjyvjzondrtmlewrxvtjcpmaqtnsliibznrrngojbernfpnemdooduiyvnuczyqquqdthfffgpatbofqkfzvjcnvmximonkmdhxtgdzhevsknuqghvqznpgqoxgggwlazsjdklwdivooessifvhciecxoyjfcsjjngpjjpiojjlswbvztywyixrkxpkhadjxchlqbxxvediyoaxfdcjnpyohsfbflyjxmztymkwkokhbnjzamrvdgccfdlwxzzjztocsmvbjncnuvmusubbyjsnpkbglyydetcwrpbhejmfroikkbdkwjjiknstolbefkhpmusjturrolxqkyrpueuvtkrrlijwtkacjekiuqfjbkljsjxwzdyjvaafwgpxenbgupkanukljcxgqatuoxilsuqfrifjsrfidshhidetmfpopyrhzynuyuyhakzufgkazeiqvrohbjhywqxwdjzdiwwkqywclwuceizpkfzjkiffxvvfvivvhubdikumpdbjfotfpbhdfjohtqubkbahoytavdvmdebqzpuetksqhfcdydqcpmqrojglggumuffvyndocrgvkqixztyqxctwwuzmvvexzxfkxxnpdghoplmrvjhgardmsevqjvdbjlxopqtqzbeagdflmjfkrdndwjsskqfbiyftkscogocmiuumkzqnqiogqbwxebedivxcyqgwmhyzucjdevkgdewmiqcdotlaatyxskzeyxzxirypdndzhrjjlbvstvsvfygsoqtcmllnmifmzlhztcqkwmihmmghpaaedecxqadeucinbzsyeqccfttwpcvuafztouxjhwmhzxnadnsniwktzzbekztpnirnntkdeyiqryxkcfwbkyfbjjgjdrodehgqwpgnwbqmvizdxqcocjvhmuiaxczerxgyucdqmlvlacynucvmjkszxrkeoowaqzdrdcvioeqcykuwzsoeraochpomyvgisxvzcytddlkchookofsgtgigvukiphssauvpdkodgqsyoiqzbqjidypgnkukungkhzfzqmplyruxyamjauaqnpxnpjiwrxjsaoosywargyklgvpxbjzhwmopgxuuifniwidoeomqzmmtskhheomzooirazvxiwzkyplntzssowqhdceblmncytfmxdusskuhftlbrwuhdtzseatlffiwsqbgytnyngisiznwowjonpeegibxtleivhvsuxwuxmjnftkwvtlffktszvdfxmgxtkfkbkswavimojatocfytamaexuccxmlmiygbfsqzqqwkymlpmtctjhnmfqtpuecjoqbymdsnlrjgdfhaagpztvlylqhqcmxssednizromzizmkhksppcuxkabaimsbcmyyrjygbhggawighrxeonueefvpswgkgvphrqbelnhavjqrxjgazvbfzzjtftedjefsvfpxqsmfbzryknhxfbkxtqpkqdrwyxnhpzwgyyxxjrfjrzfgmmrgljxnfllvyasacvrtpedewzuryxwecefxqwiebswbzfyrnyqeyjrzozpfhlsqzneuxzbbtjuwlflqasthrphcegeafjvtlcyokadqvayhmxsirhzdbojlrvbjtdexpmledbpifuyarqebzutocomtvidmtxeghbczoegnehazbslavqvwzuluzyimojdlbnrtvrsbycijfrubcvhmhmblumfsmxeatiynzhrdhuypuzuwcukyhvpwesolpkvsfxmocufsezfllqikszgdmdsbljminbdskiumymgvnvvvokcmkrpwiphahyjctggfjfbuezejecbqbahwzljelhzxdfdwcmdxipgfczsejxydyewtjrfmyijsqpxayfgbbqfdbjblfdtsraemvehwtkqcekhcsarhtrgicaithtmitnwppbvvtmhihconesvwvmgraecmskglkjptkjzwhcfddijmnshanyvlftperzfxpgccemschpdbemytimjjqlumfqhdbdyykpgeplhwzzokfajaqaeyjfvqgbpaokynqzhgvxckvkxjyfyqrzpijubikprvjozzfvvavlvqhcwevhssjvjgipokegopyfrfffspakxquwtauewztfjrssdmezsaofpwcivroxufzumqarxenowlbwptniayyjnmvchfnqjaeoipskqisoewtzdzoohertdxpfygpgvebqrevbigkbdmdcqrscyrvibgionhodfrhytfvxtrafvtqopatvmtasctxbwmjvhwglvj", 10) == 5407)
print(Solution().longestIdealString("wprwcytrvmyfzuhbgrxwzeewiwqbwervdsmamukwnuqkianhkaqoqermhfbeisrljzhmnszxunvfmqpnplbdyjzlgkykikxdteciklkyycmwavpnzxdedckrayuttavufwigwgmvkaexmaayhqkzsngmrlllbqoyabdlhkszshuhjvpzjvayikesygnpxyjtowlzvfgvdgqxgrlgdfsudirkvwnfalytpdvyaijfwvitsqsozrmnfazjqypcajssboxtijxqnnknefdfoevnoxqbuhsxbyaihtewccorpjeepdxsdtbfiajbanfxiftponyxaiafupbdzqpeydjooecclpygyomfxsydtgnyflpanjgdvbeepmbgklwgizagudfjgzliedevhgyrdpfshtlxfklyzotfernyruyatssdtkklnghpuqmobwhyvulvnzumerubvcxrdushvkhyaxvewdaetgcqkqjhckvvrnltdenrwyzktflghzsmvyeatldvgypopposzhjfjzovbvqqcobavsdwrjgnhcuboljufihburnmvxzbdkoguamxayizfenzdjphccxtbuhjjvdfsleszwdelnppplbnxzbvaxtxyxxtjgqdfnockocyrsavumvjmxehsleaiyzimtupcvembdbdzjvxignempujuludurbzgwapigzmbebrbsrylhhfuyswcubmjtyhlwuayawnsnxsgrvbatwoaebabxaxgjaxrkbmlxmjvnoxkymkfmvhsptcyizcyytczbtpxpwudzcbnjklopddekttktwadspclqiaeogmugzroefndrjwizcofhbkfhcgekpxkcgdkxkybpkgudcunezhkyvyxjdtgbstmizmnqbrogpmrcxpwsgycgmracialchkssnuzsqdlcnnsexwzrnlkkwujdhrczysbughdzjqdxhqwwbpmeqnjnqxtzldajdxsicbkevxhgewfhhynkufaysumvmynuiakwajpaaukuoxjdshztgnycfqxhpyhyhcdzuihssklorrqkkkoyyeyllytzebgezobhtlxjepunnnfsarltezukaxkwydvlnmriujgxphnujcqxspwlowcaoapyfnreegrrlmuzvorwdhhybjssgqiprsbwmolhqmbxmdcmdsrzmepegcbabuznpytunymwqqnagllhhhqetimwxonsjpwcavsxacixcnxuxssnalexndslhplfqykrusccxjqapaitkrejxvxhewhzqjzhqhgmekxoeibrwmcjnwchvxeibkvldkcxmzavdyhlcupomwurcqwwefowcbllixjowkrwcmuaypghighfhlswudfplrpcmemxnvgjqloyjmfwptaehqqliwkzsiodfrufxvbwhrzwskuqegxbsxozzfgitcsinznxgutvetuifkkoislsfntoppqjcmmsnxviiatitlsjffvhfwqvzcmjbcicqsyjzqhokgylarlhrbmsiiryohlzpxznhcfsqsfdzgfjlmkajoseaztktaluxclurjmqgriutsptmxglehqbrtxrowatceginootgbcuvrvtgppsnzhxtkblyzffqucxwessywswbubwpdpdninovejzhtldvuokqyrvewafbermfyauoljaemusdaiujlmjjvecixiuauvkmikvjbrutkepxfxqzifdftjiqycivefdhiepdzlnztkgizpbzkbnhvvegfrlrcufxlnyuyubcvlbptmohyogcorndxcjuudvjcfjcwubdqloshnviqbxqhbpkkuvwjrcmurjckcqysffwghuhcniuvuyuecwcovvnzfalsapuztfmlecjmvoxfvpxivuezynsowwlfzudbegecuqeuadexaynqmsmxnzmpsvzvawfoazeymnbwrrcsihiahagpgltlrodxmuzscujvwaxapxiovfrdqvjrptrghxkijcqkujauigtudzxxevgqpkjabbuhworviibjfbhxfffydzpqzismdkoipdhsbxppcqfdkwlybktrgnobmyncjrdnhjlpqrogsdohqilywgcjmjjutsbbodafgagxynsoznuvvmuolckogphnhpqwfobscewitiytsdgjrbhrgdmypzyqvuusuljxeinamzmqwaftasecnabzixlrtewmzhkrqgujnehupyfplqiwbsmrcozgsfunvqviyykndlyyxgiefrpudhounqocsqhuuzyhlqlxtwjpjndbryddtbrqajfyqoeoptaonxizegempakgrfetwaltgxhvbxfdvfszkpcvekmcojfgfvoarbkbhtyzhopdghmusbbhxwvcggxkzmxeecdkhzcatjmaxerlrapenmfwibezcgodmsazrezxbsjrnqnjzwrbywmsoropmmzjmbjbekxspubjkcqtqlmcabrbtsonvylfyzuinvklipuaissfwnaosjzfdpqkpayxxntonkwtxhentdkjozryvqwuzojezmijxicsnumezxahwpnitmlxdtzwjoxzqcvsrduupcitpylummwowiwdryrmsvbrcrndydjnjvryqwwaibfvvqonbuulccfaqcvpmjcyctnecumpmfihymhjsszjwldjznjnuveifghutcoehynvktlvzlvrhlfgajqolvoosvdoibyycrppnzacsbrumctehmfoyjvmqbhkwvkijoysbhbozwwihcogugcwguqzpqxygfqxxwblowffzkrppqznxrtqwypvuwahsvolqaynthpyayymvqmqenjawssxibiyrbzqgjqnodndtomzigkcvtglwkdvfcfhqhzcljpyfdnokdtricxpkcmoqaiuvvmuuvsgqsjuprouxsmaguixdzqebrkmqkwrheepzkjnjhkxnqjhgutgojenkngaxuvopeurnuoisnmobvrrjvftjbdstfpwticzuxhvmbcgojhdkonvfziavsbfryzaexxxmjdnbdpguzulnzfjzyrmphszoadntfpasqdbljnebkqewazmzcpmpjzpkdkdvowlvcyvavaxdgazhuvqjenokkdkqpoevkebsqkbinwnbysuhxvxxyqgxptgmqtgjninhigbsbyksvedbqwmgasxirgmxghfsazvqoxbivglrilmtlzrlzknjwumycgdaipdyxemhvnqvjmyzadjevwhmiwoidbnhvlrnkskerfljthwmwbkkslzvpoabeevhsjlfqvdfgztmumlsvlsqdfsusegxigzaxglwgolvnrwgzeulbgmcefzwvzsvnqjuixnzpwwiihrfgnczyayndvbuomusabzookcudcszsvwwnhamzxjxtikkqwbmblthgyyurmekleqxbuhxmoddtnyezkeojqihhezqrfrarkagkvzyzurssfbqvwxshocncypthqjrjqmvoztbwlhzpfozfsgddfjfrppfdbszipqvlkvkmmrzwvnsnvffiqgemrphlgjwldlaxjvypihjcfinaucuccrmwaosbsvcczepmabrtvuplsgigccfmnmajdfshbvfhgprelgybrtpemmujxiopjjjzasudbkkkpvuigtqsqnsvoksdmckbmritufgiatdnpjenlhzvovacluxqnjqjjzrcgpeubeajfxomumekwnpiwbbbtoaeljenohpfyfdkemgugozzqqzaofnzrdebqyslexbgorxnqplehfnnurpndjflsohazfiahesuwvghirsuxpeprxlffbsblujamtomfbndiahdczivbttlokltejxqnwxcipmxuasoctuonspipqzeyghysrpydoepereeedovccruhnsrtgdikciryjcqaymdruwceaupfurvffwkkdudtlwdpdyrydtiblnkhusatmhmbpyztidrgmtmfyrqngepqmilsvelfuvawyiwjmljmxkdwpqvdxtzibndgtjcsbhzfrlzkxpzefmmrggqkejuhznbyezzqkpromfjbdugeiezsrjxeztjctkzckctzjyyfaddomduzhbshidqmhcgjegmkfsfimpbyyyzarqqvnlnuelafcofmlxtjpizqekcjshvffunsangcjhsfgjiwqvafeggkqxblluwiftvwkhfogtkzqknbsjexicpxpytasrkyvznwijlpwqogulslbwlpimgtzyvcxyfxglfbdiofmttemvzylmyfjjbaszsjldpjjlihsisuzrtovyodnpiyvtlxrsjuvxidwvmanspabtmwhhhfedkxdwvrmeedzkpovdmpblmfnofyntnovuvmychwabegrszdqhprtzfezodijhamrwmdjfraumbahhfbcozlnjvdukmktsryecfqmpgczedfapdnkuthdcgqojgkhwolmkogrqzniwurlwqexbhdsoxquyjimuraqsjnllbndxwzvoaoattgxcotzdluxtpiluqgpywyflggnakzgkkyoaewngcxmlfnailfzycofpkwwrqjaqhtirafkvyljyykplymgtegjsklwhupwvfrnfojjlmumrrtlmcwkulptwjnvfboouthteqfchnvkialazjkayqwrszwisemczezhqungsijerlbrvnsdckcpzplkdtdnowqshbofkecvipahvwnjnknzufpgrcrvocqsfeptahyyehkarwonfttxqfdnrknrcaximsxpoleevvixqjctlokoqodqlbahuspzjxvoaxxlatzbafbjxjwyfnxiqnlhbbdpgljtgunvadujlpdqdqvwoprtkegrwzsmuqzcwtumuoorcdgiwyfhbcrzjmdzuyxemnbxlwrlweobyszyudfexfxbhbwtnpmlsaqahvmtzvhihniyditemzfvczinutetuuxenupfxtzdhtgeuuwjoqcnpwjgryozersznkjyyumusqchiumlmfyczkudniawjtwowocpklrxbonlggeyfrxgkeijqtbnmuodfpmkjjmlfohkdyxlsmetcafyjrhaysailmezckuphxzwyedrfodafchztozhajmzkvuzivmwovsekrbqcatdhuaydbuafsqhnwuhwycjycjmyorqaxdstfvyzkstznvvbinzrxxhktszvdzaurgisvkpnvqaiyjrvhfiopytuwqaxhkgnboeanbaodrqtivgpgpcwgqhmeoajtbuvwrhtgpcgdmxurbkwixlxlbiozugasjzlnsvfopkuqjcylkzjpkwwzbrgvqopmetnpogwnspbmkpsmnkfwtpltozhzfoikbzoqngicfujgjqepuiyjzosypsyxdepwgigrzgspgvizhszmkmurbagrngcjvbvffiznfktlronunmftpewnypscfkjdqixzzawpoejgshoeaodwipakzhqqeomktfxcvqsimbegjboxqqpghvuxhfexqnmhdghdmorymcrvqwglccylqslqudbidqalxlyldusjplaaoiztdqozjfhgmepkdpkdskenirwbkvinqovhfsukxktgrgcqbehmrknmfnrmztfvabjmohawqpluzgiowuhnixzaimppludurberipruffrciorjhjezceqwersojhdpjnckpmrjfneoywkxtihhkbsexupgvblygwbiupfrdlmrpihngfhcydqmbsmroitelcmyxhfsqhwclikdlrypfaaopheqgqbbrmsgzpeioekrjijpjpjzozoivbkydimxxepgcfzzaqjwwncpxmwoswsumzfpsbxctooufosnlhqxxrogtsdaqganzbcwhittwzpalpsnblojsnxvezgdlxjugoooylevfsorksuqwfirzbqzvxqcwaudglrdppmiwyopgrudrftiwdzualpswtmtampyuhycpfnlwfackvaflbhmzxfzobavuircaysovrayfulyzkpozwsftltimkvblykghaubabcmvvlegosxttvzgqlkxghgyryuxbfwkvhvaxqlxvlybecakmtqzhwldmcdlhofwsqqhcgtxrthvufnoheleyglffhpzxmgzjpkzscunsrrhcgrafyssfxnpjzlfuqrcvqraklipptuqdpiskvzbphbzjotepdkrnaqxzsrdiglgpqnikxdxmtacpttpweufrqdmysoehbikkrceegoippuueawphghigvtkiuehrscivehedsibbiztvgwhglmxetuvrqqetwiesphcghurcoypeyvbcazuvpqfskmpkuwxvohqteqkopsrvhdefcygygatfxkoehxbzaugmjvqtjlfgowgvhgpcfxyqylwuplqhrtboxesegiuhkmqyzuafsqubtcpcsfwtqrayibcnxptcepirdfzvgmpcniubhcbovnsqqbxqwpssuaaswsnzatuvmxtjlrscldkzhukfwgqexsuatchzxmtfruigbjmotmjabbobypglyruvwdavsaihsjeuzakgkiiqlisnczppxbttrtkngyajnzmcjsuziadzccbixjcadmdfypbksyowgoczdzbdqgpkpgbbvkgbrivjmykvzowixllhikjbiwjbwhmsvsppkqrptlmmrnmtthkbzelrdbitypqmuijsjirvshgzihrygmzdthqqdnqpenuzxiaoeogtmmrxjxsiteqfiwgptmjuzqphclmztpdcpctdwbknottzuofkuavnbjxtvmqyvqegqdvftnmpxmcbkxkqsufaigdxazhzlxtdtrwszaidxkopnairksvhmgzrcsqxzapyjnffcrdfndypioajbdduftgwzosolnlxhvciwgyrblprnnrefhnmzeucaztujwhoprrubpyxagpjxgzpwkrsiuhgieyxstypqacwrtualqfkzrewkhdqphccmfgggtjwyjmghwglhyczdejxvowexzfehcwsplnbezyqgclkczqkppzmsgmkkevmuijaiomwtvcahuaymgwlrkqmruylttrlayuakfiikpsbowydtahjfilyvsndhtdutfiderbztsfggxhlzvuiluijajtfiuqbccplnpgsnlhbrmojblzghiqvkxplejkxpqtuayahvovfzkjxzipvxktltzdhnfcsnctagiowahfrhjwkescpcxcxwciqfygnwzkgbxodpmoagcngtwclmzylfgprcmyrheyquwziyftmrsddvtzgfpyygnxjlttbszevsivhkfzuhnvggqsxpcoaplyxjgikanntfhppcejcydnhwgzuvnpdxosyvkwlclvjfhxycoqyvtqhxnquojpcyhxosbotmytsguzizovgcunqvonpyiktelqildyuetoquhduvsljyjicswhatzwrxcykmgtmcrnzceukstegbpayluujteekqdaimfiiqoztzwuoscpuqyyhkuoyxhzfpwcmdkmtqwuqmzpmywggnoisqgwgfumqcnkdtazngxnylbtdquxczumzmchtqqpivrjuldxljptwjcawjejrbmioifrvjgslccvnjazkqfkmgwddjoznpvfrkgstaxymopmecfwcdfesyvrxrakspdunibavjdcirrwzmmlraeipuvcdritjvskzmhbvmtcdhsgfexugsfftcdtqvnvvcqwmadggtoxrrsbjmkylumztjoyvjqfqpjlxbzzkmuilctmkvjgvnnaklsggrgbmzkymnaralxeemnzvmtjdmzqqrqkczielzkbgzvjrsfitwlsklqrjollmabgmjozzatlwlbphdkmxbbavqurqodzzdjwpbhrxotswqfpkxhatxmhxxbkbgvgyjkuyaqpwoxvoyzyqfndhlsbkvralcmenalhzyqttfsdfngjszogyuijfqirpzmepsgdbeacfevbwmgtlbddxduabrmruldiowyvqtoghumtqrwufqcquavvmjrafvvwfhatilgmlhvpcbucmaryxbzbejxfxhwnwnubqxrtactvdrnztwtkwfsvwgatvtytzmhjnhbjfftaypqmtxflkswifrvhpmsmrmlzbkysbnhvgxifcjbohsmwrmyjlsoutwcgxjkkbhzhwpkobsvxnihojarpnkuwjomxcajuwhygukywpdeurkkhwstacrmkorpsnknrgaoocpmjtyjufveycqvbolfnsvkjtbkcggpwdyczfkicfqwgebuosflhooswmfnlyoorlqwyynfppapoxjwiquoxdeydmvrrqinnufuwpvxagxqmxabkmsliqjrpsddqudrkldqghifnkbrjtvapicmbnmvuwntlapkjvofyxvmnxyzqbkhixiljbjrbizktgbhuhvggqbnwgibypzngmpawsplldovuqzrzhogswgufchwntgkirdpdbdpjexcdanglafhphtmkppamhnbmccdlvvqjbhohyvfcxrmgdmbfdhzvmsbpmlzjnrfbykxzbhmykysetsblcxcrgddetaaglepketwytouwkhfkgsnjcuekpijpycgfczktzrzlrsmettepsglvpirhgbhvmvmfjwgnleergyecnjkxaimdunfmtrkthybkuhs", 10) == 6148)
